# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'TapCardCheckoutExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TapCardCheckoutExample

end

target 'TapCardCheckoutExampleObjc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for TapCardCheckoutExample
  
end



target 'TapCardCheckOutKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TapCardCheckOutKit
pod 'TapUIKit-iOS'
pod 'TapNetworkKit-iOS'
pod 'TapApplicationV2'
pod 'SwiftyRSA'
pod 'TapKeychain'
end
