# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'TapCardCheckoutExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  #pod 'SwiftEntryKit'
  #pod 'SwiftyGif'
  #pod 'CollectionViewSlantedLayout'
  # Pods for TapCardCheckoutExample

end

target 'TapCardCheckoutExampleObjc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for TapCardCheckoutExample
  
end



target 'TapCardCheckOutKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for TapCardCheckOutKit
  pod 'SwiftEntryKit'
  pod 'SnapKit'
  pod 'lottie-ios'
  # pod 'TapCardVlidatorKit-iOS'
end
