# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'TapCardCheckoutExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftEntryKit'
  pod 'SwiftyGif'
  pod 'CollectionViewSlantedLayout'
  pod 'LocalisationManagerKit-iOS'
  # Pods for TapCardCheckoutExample

end

target 'TapCardCheckoutExampleObjc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for TapCardCheckoutExample
  
end



target 'TapCardCheckOutKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for TapCardCheckOutKit
  pod 'SwiftEntryKit'
  pod 'TapCardVlidatorKit-iOS'
  pod 'CommonDataModelsKit-iOS'
  pod 'SnapKit'
end
